In [1]:
# Tanmay Vijay Jadhav (20121040)

In [1]:
import pandas as pd
import numpy as np

data = {'first_set': [1,2,3,4,5,np.nan,6,7,np.nan,np.nan,8,9,10,np.nan],
       'second_set': ['a','b',np.nan,np.nan,'c','d','e',np.nan,np.nan,'f','g',np.nan,'h','i']
       }

df = pd.DataFrame(data,columns=['first_set','second_set'])

print(df)

    first_set second_set
0         1.0          a
1         2.0          b
2         3.0        NaN
3         4.0        NaN
4         5.0          c
5         NaN          d
6         6.0          e
7         7.0        NaN
8         NaN        NaN
9         NaN          f
10        8.0          g
11        9.0        NaN
12       10.0          h
13        NaN          i


In [2]:
nan_values = df[df['first_set'].isna()]

print(nan_values)

    first_set second_set
5         NaN          d
8         NaN        NaN
9         NaN          f
13        NaN          i


In [3]:
nan_values = df[df['first_set'].isnull()]

print(nan_values)

    first_set second_set
5         NaN          d
8         NaN        NaN
9         NaN          f
13        NaN          i


In [4]:
nan_values = df[df.isna().any(axis=1)]

print(nan_values)

    first_set second_set
2         3.0        NaN
3         4.0        NaN
5         NaN          d
7         7.0        NaN
8         NaN        NaN
9         NaN          f
11        9.0        NaN
13        NaN          i


In [5]:
nan_values = df[df.isnull().any(axis=1)]

print(nan_values)

    first_set second_set
2         3.0        NaN
3         4.0        NaN
5         NaN          d
7         7.0        NaN
8         NaN        NaN
9         NaN          f
11        9.0        NaN
13        NaN          i


In [6]:
import pandas as pd

df = pd.DataFrame({'values_1': ['700','ABC','500','XYZ','1200'],
                  'values_2': ['DDD','150','350','400','5000']
                  })

print(df)

  values_1 values_2
0      700      DDD
1      ABC      150
2      500      350
3      XYZ      400
4     1200     5000


In [8]:
df = df.apply (pd.to_numeric, errors='coerce')

print(df)

   values_1  values_2
0     700.0       NaN
1       NaN     150.0
2     500.0     350.0
3       NaN     400.0
4    1200.0    5000.0


In [9]:
df = df.dropna()

print(df)

   values_1  values_2
2     500.0     350.0
4    1200.0    5000.0


In [10]:
df = df.dropna()
df = df.reset_index(drop=True)

print(df)

   values_1  values_2
0     500.0     350.0
1    1200.0    5000.0


In [11]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'values': [700,np.nan,500,np.nan]})

print(df)

   values
0   700.0
1     NaN
2   500.0
3     NaN


In [12]:
df['values'] = df['values'].fillna(0)

print(df)

   values
0   700.0
1     0.0
2   500.0
3     0.0


In [15]:
import pandas as pd

data = {'A': [11,22,33],
       'B': [44,55,66],
       'C': [77,88,99]
       }

df = pd.DataFrame(data,columns = ['A','B','C'])

print(df)

    A   B   C
0  11  44  77
1  22  55  88
2  33  66  99


In [16]:
df = df.transpose()

print(df)

    0   1   2
A  11  22  33
B  44  55  66
C  77  88  99


In [17]:
df = pd.DataFrame(data,columns = ['A','B','C'], index = ['X','Y','Z'])

print(df)

    A   B   C
X  11  44  77
Y  22  55  88
Z  33  66  99


In [18]:
df = df.transpose()

print(df)

    X   Y   Z
A  11  22  33
B  44  55  66
C  77  88  99


In [21]:
import pandas as pd

data = pd.read_csv("C:\\Users\\Admin\\Desktop\\DSBDA LAB\\Matrix.csv")

print(data)

    A   B   C
0  11  44  77
1  22  55  88
2  33  66  99


In [24]:
data = data.transpose()

print(data)

    0   1   2
A  11  22  33
B  44  55  66
C  77  88  99


In [26]:
data = data.rename(index = {0:'X', 1:'Y', 2:'Z'})

data = data.transpose()

print(data)

    X   Y   Z
A  11  22  33
B  44  55  66
C  77  88  99


In [2]:
from sklearn.preprocessing import StandardScaler

data = [[11,2],[3,7],[0,10],[11,8]]

scaler = StandardScaler()
model = scaler.fit(data)
scaled_data = model.transform(data)

print(scaled_data)

[[ 0.97596444 -1.61155897]
 [-0.66776515  0.08481889]
 [-1.28416374  1.10264561]
 [ 0.97596444  0.42409446]]


In [3]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler

dataset = load_iris()
print(dataset)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [4]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler

dataset = load_iris()
object = StandardScaler()

i_data = dataset.data
response = dataset.target

scale = object.fit_transform(i_data)
print(scale)

[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

In [5]:
from sklearn.preprocessing import MinMaxScaler

data = [[11,2],[3,7],[0,10],[11,8]]

scaler = MinMaxScaler()
model = scaler.fit(data)
scaled_data = model.transform(data)

print(scaled_data)

[[1.         0.        ]
 [0.27272727 0.625     ]
 [0.         1.        ]
 [1.         0.75      ]]


In [6]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'Income':[12000,25000,30000,40000],'Age':[20,30,45,56],'Department':['HR','Legal','Marketing','Management']})
df.head(4)

Income  Age  Department
0   12000   20          HR
1   25000   30       Legal
2   30000   45   Marketing
3   40000   56  Management

In [7]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np
df = pd.DataFrame({'Income':[12000,25000,30000,40000],'Age':[20,30,45,56],'Department':['HR','Legal','Marketing','Management']})
df_scaled = df.copy()
col_names = ['Income','Age',]
features = df_scaled[col_names]
df_scaled[col_names] = MinMaxScaler().fit_transform(features.values)
df_scaled.head(4)

Income       Age  Department
0  0.000000  0.000000          HR
1  0.464286  0.277778       Legal
2  0.642857  0.694444   Marketing
3  1.000000  1.000000  Management

In [8]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np
df = pd.DataFrame({'Income':[12000,25000,30000,40000],'Age':[20,30,45,56],'Department':['HR','Legal','Marketing','Management']})
df_scaled = df.copy()
col_names = ['Income','Age',]
features = df_scaled[col_names]
df_scaled[col_names] = MinMaxScaler(feature_range=(5,10)).fit_transform(features.values)
df_scaled.head(4)

Income        Age  Department
0   5.000000   5.000000          HR
1   7.321429   6.388889       Legal
2   8.214286   8.472222   Marketing
3  10.000000  10.000000  Management

In [9]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np
df = pd.DataFrame({'Income':[12000,25000,30000,40000],'Age':[20,30,45,56],'Department':['HR','Legal','Marketing','Management']})
df_scaled = df.copy()
col_names = ['Income','Age',]
features = df_scaled[col_names]
df_scaled[col_names] = MinMaxScaler(feature_range=(50,100)).fit_transform(features.values)
df_scaled.head(4)

Income         Age  Department
0   50.000000   50.000000          HR
1   73.214286   63.888889       Legal
2   82.142857   84.722222   Marketing
3  100.000000  100.000000  Management

In [10]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np
df = pd.DataFrame({'Income':[12000,25000,30000,40000],'Age':[20,30,45,56],'Department':['HR','Legal','Marketing','Management']})
df_scaled = df.copy()
col_names = ['Income','Age',]
features = df_scaled[col_names]
df_scaled[col_names] = MinMaxScaler(feature_range=(5,10)).fit_transform(features.values)
df_scaled.describe()

Income        Age
count   4.000000   4.000000
mean    7.633929   7.465278
std     2.079290   2.211708
min     5.000000   5.000000
25%     6.741071   6.041667
50%     7.767857   7.430556
75%     8.660714   8.854167
max    10.000000  10.000000

In [11]:
import numpy as np

data = [1, 2, 2, 2, 3, 1, 1, 15, 2, 2, 2, 3, 1, 1, 2]
mean = np.mean(data)
std = np.std(data)
print('mean of the dataset is', mean)
print('std. deviation is', std)
threshold = 3
outlier = []
for i in data:
    z = (i-mean)/std
    if z > threshold:
        outlier.append(i)
print('outlier in dataset is', outlier)

mean of the dataset is 2.6666666666666665
std. deviation is 3.3598941782277745
outlier in dataset is [15]


In [12]:
import pandas as pd
df = pd.read_csv("C:\\Users\\Admin\\Desktop\\DSBDA LAB\\Students_Data.csv")
df.head()

Name  cgpa  placement_marks
0    Alex  7.19               26
1    Brad  7.46               38
2    Joey  7.54               40
3  Kishor  6.42               52
4   Viraj  7.23               58

In [14]:
import pandas as pd
df = pd.read_csv("C:\\Users\\Admin\\Desktop\\DSBDA LAB\\Students_Data.csv")
df.head()
print("Mean value of cgpa",df['cgpa'].mean())
print("Standard deviation of cgpa",df['cgpa'].std())
print("Minimum value of cgpa",df['cgpa'].min())
print("Maximum value of cgpa",df['cgpa'].max())

Mean value of cgpa 7.168000000000001
Standard deviation of cgpa 0.4437003493349989
Minimum value of cgpa 6.42
Maximum value of cgpa 7.54


In [15]:
print("Upper limit",df['cgpa'].mean() + 3*df['cgpa'].std())
print("Lower limit",df['cgpa'].mean() - 3*df['cgpa'].std())

Upper limit 8.499101048004999
Lower limit 5.836898951995004


In [16]:
df[(df['cgpa'] > 8.49) | (df['cgpa'] < 5.83)]

Empty DataFrame
Columns: [Name, cgpa, placement_marks]
Index: []